### ISSUE TITLE
'chartsample-Swift.h' file not found

### ISSUE THREAD

**Issue by alfredangkasa** [danielgindi/ios-charts#87]
Hi, 

I already do :
1. Drag the Charts.xcodeproj to your project
2. Go to your target's settings, hit the "+" under the "Embedded Binaries" section, and select the Charts.framework
3. @import Charts

I also create a .h file call ChartsDemo-Bridging-Header.h which contains :
#import <Charts/Charts.h>
#import "chartsample-Swift.h"

Whenever I build the apps, it give me this error :
1. /Users/alfredangkasa/Documents/Mac/SIMPLE APPS/chartsample/chartsample/ChartsDemo-Bridging-Header.h:13:9: error: 'chartsample-Swift.h' file not found
#import "chartsample-Swift.h"
2. <unknown>:0: error: failed to import bridging header '/Users/alfredangkasa/Documents/Mac/SIMPLE APPS/chartsample/chartsample/ChartsDemo-Bridging-Header.h'

Anything wrong? Thanks.

![screen shot 2015-05-14 at 9 05 26 pm](https://cloud.githubusercontent.com/assets/12422209/7633349/c471ee86-fa7d-11e4-9228-6cdc2a0a1927.png)
![screen shot 2015-05-14 at 9 05 37 pm](https://cloud.githubusercontent.com/assets/12422209/7633350/c4ca4cac-fa7d-11e4-8edd-578188f64b15.png)

**Comment by danielgindi** [comment]
You shouldn't create a Bridging header.

**Comment by danielgindi** [comment]
Read the instructions again.

**Comment by alfredangkasa** [comment]
Just fix a few of my code, but now I'm facing this error.

Do I miss the library? or I did uncorrectly?

![screen shot 2015-05-14 at 10 13 42 pm](https://cloud.githubusercontent.com/assets/12422209/7634691/cfc594a0-fa86-11e4-9f17-f41d7ec10c5a.png)

**Comment by alfredangkasa** [comment]
I already convert your code into Swift version, its worked. But why I'm only get 1 bar?

Did I miss something?

![screen shot 2015-05-15 at 12 10 00 am](https://cloud.githubusercontent.com/assets/12422209/7637279/f9053ed2-fa96-11e4-8725-74a6ceda4989.png)

**Comment by alfredangkasa** [comment]
Hi, thanks for your code.. I just convert the barLineChart to Swift version perfectly. 

But why for this line I keep hit the error?
xAxis.labelPosition = XAxisLabelPosition.Bottom;

**Comment by danielgindi** [comment]
You should make sure you are using the latest Xcode.

**Comment by mmckinley8** [comment]
I'm having the same issue, I did not create a bridging header. Followed all steps correctly, any ideas?

**Comment by danielgindi** [comment]
No need to create a bridging header. Xcode creates a bridging header when
you declare your project as a mixed Swift/ObjC project.

**Comment by alfredangkasa** [comment]
@mmckinley8 , no need to create the header.. Just follow what @danielgindi wrote.as simple as that. trust me. :)

**Comment by mmckinley8** [comment]
I know, I said I did NOT create a bridging header. I followed all of the steps exactly, still failure to import bridging header..is this because I already had a bridging header in my project for other frameworks that I have imported?

**Comment by alfredangkasa** [comment]
@mmckinley8 can you upload a screenshot so i can see? how about the build setting?

**Comment by mmckinley8** [comment]
Yeah, I will in a few minutes

**Comment by mmckinley8** [comment]
So since I am using swift, I do not to #import <ChartsDemo-Swift.>???

**Comment by mmckinley8** [comment]
ChartsDemo-Swift.h

**Comment by danielgindi** [comment]
If you are using Swift, you do not need a bridging header, and never have
to import anything

**Comment by mmckinley8** [comment]
Okay, now it just says Build Failed and doesn't give me any errors.

**Comment by danielgindi** [comment]
And ChartsDemo-Swift.h is the bridging header for ChartsDemo project. Not
for anything else.

**Comment by mmckinley8** [comment]
"No such module 'Charts'"

**Comment by mmckinley8** [comment]
This project is using cocoapods, I don't think that should matter

**Comment by mmckinley8** [comment]
![screen shot 2015-05-21 at 11 33 45 am](https://cloud.githubusercontent.com/assets/11301364/7752411/486451c8-ffad-11e4-992c-cbc969e1ffde.png)

**Comment by mmckinley8** [comment]
![screen shot 2015-05-21 at 11 37 59 am](https://cloud.githubusercontent.com/assets/11301364/7752504/ddee2296-ffad-11e4-9136-e406d5195d1a.png)

**Comment by benrivero** [comment]
Hi @danielgindi very awesome work, I am creating a demo for test the library on swift (when is finished I could share over github the project because I noticed that many people ask for help on Swift), anyway,  the project builds and runs ok (with no data, am still on that) but now I have the same Issue of @alfredangkasa 

Error with this line: xAxis.labelPosition = XAxisLabelPosition.Bottom

![captura de pantalla 2015-05-27 a las 11 24 39](https://cloud.githubusercontent.com/assets/306991/7841612/639bfeae-0463-11e5-8ac0-60943cd60cef.png)

Thanks in advance, and great work.

**Comment by danielgindi** [comment]
Try to leave as it .Bottom and not XAxisLabelPosition.Bottom

**Comment by benrivero** [comment]
Thanks, it Works!!!

**Comment by raju123lexicon** [comment]
Hi
I implemented chart graph in my mac book successfully,but  when I run the my project in another mac book it shows the chart.framework is not found.Please give me solution

**Comment by ReneVella** [comment]
Hi Daniel,
I'm using Xcode Version 8.3.3 (8E3004b) with iOS-Charts 3.0.2. i have created a new project and imported the iOS-Charts using Carthage and followed your instructions. however i'm still getting a file not found error on the #import "iosCharts-Swift.h". Appreciate if you can help me as i have invested a lot of time so far with no resolution ? Below are some screen shots. Many Thanks

<img width="862" alt="screen shot 2017-08-01 at 18 46 21" src="https://user-images.githubusercontent.com/30633629/28838915-c73ff56e-76e9-11e7-8902-6be148493621.png">
<img width="943" alt="screen shot 2017-08-01 at 18 46 04" src="https://user-images.githubusercontent.com/30633629/28838916-c77ee1d4-76e9-11e7-8ecb-fdcb53cd4d45.png">
